# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91b6500b9cdeb51480274d87d34e782ec63e364100f282809300c061d45f857e2ed4b0a800812d13416cf0746220a0dce8d40c47be5b4ff7772a3ccf8a249eaf

test:
  secret_key_base: fef335a0372b3e0f97bc654aa28db6f6a42063ee1742d0394f7bbe09187a20068a003e55380712870fb6ba301dcba2b6e90a7538c2000c4221f7071ee010c3f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
